import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { config } from "@mini-vercel/shared";
import { deleteRoute, upsertRoute } from "@mini-vercel/db";
import { exec } from "./exec.js";

/**
 * nginx routing (phase 1 of the proxy story — see docs/architecture.md).
 * On every successful deploy the worker rewrites one server block per project
 * and hot-reloads nginx. The Go proxy (phase 2) replaces this file wholesale.
 */

function confPath(projectName: string): string {
  return path.join(config.nginxConfDir, `10-${projectName}.conf`);
}

function renderServerBlock(projectName: string, hostPort: number): string {
  const serverName = `${projectName}.${config.baseDomain}`;
  // App containers publish on the host's loopback; from inside the nginx
  // container the host is reachable as host.docker.internal (see compose).
  return `# Generated by the mini-vercel worker - do not edit by hand.
server {
    listen 80;
    server_name ${serverName};

    location / {
        proxy_pass http://host.docker.internal:${hostPort};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
`;
}

/** The URL the deployment is publicly reachable on once routed. */
export function publicUrl(projectName: string): string {
  return `${config.publicScheme}://${projectName}.${config.baseDomain}${config.publicPortSuffix}`;
}

/**
 * Record the route in Postgres, rewrite the project's nginx server block,
 * and hot-reload nginx. Reload failure does not break the deployment — the
 * container is already live on its port; the route just lags until the next
 * deploy or a manual reload.
 */
export async function switchRoute(opts: {
  projectName: string;
  deploymentId: string;
  hostPort: number;
  onWarning: (message: string) => void;
}): Promise<void> {
  await upsertRoute(opts.projectName, opts.deploymentId);
  await mkdir(config.nginxConfDir, { recursive: true });
  await writeFile(
    confPath(opts.projectName),
    renderServerBlock(opts.projectName, opts.hostPort),
    "utf8",
  );
  try {
    await exec("docker", ["exec", config.nginxContainer, "nginx", "-s", "reload"]);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    opts.onWarning(
      `nginx reload failed (${message}); route file written, reload manually with: docker exec ${config.nginxContainer} nginx -s reload`,
    );
  }
}

/** Undo switchRoute: the subdomain 404s again (project taken offline). */
export async function removeRoute(
  projectName: string,
  onWarning: (message: string) => void,
): Promise<void> {
  await deleteRoute(projectName);
  await rm(confPath(projectName), { force: true });
  try {
    await exec("docker", ["exec", config.nginxContainer, "nginx", "-s", "reload"]);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    onWarning(`nginx reload failed (${message}); route file already removed`);
  }
}
